localIp: 192.168.200.131
localpassword: uu5!^%jg
logging:
  level:
    com:
      dd:
        ddfgm:
          mapper: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
remoteIp: 106.54.214.82
remotepassword: Mg73xPd8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: ${remotepassword}
    url: jdbc:mysql://106.54.214.82:3306/mysql?useUnicode=true&amp;characterEncoding=latin1&amp;useSSL=false
    username: game
  freemarker:
    cache: false
  jackson:
    default-property-inclusion: non_null
  mvc:
    favicon:
      enabled: false
    static-path-pattern: /**
  redis:
    host: 114.116.237.15
    password: 19970505
    port: 6379
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
